### ISSUE TITLE
MongoIo: find & update: multi

### ISSUE THREAD

**Issue by matmiiiin** [pagesjaunes/swallow#3]
le mécanisme actuellement mis en place ne met à jour qu'un seul document. Il faudrait activer le mode "multi" (par défaut à false) pour mettre à jour TOUS les documents qui matchent la requête "find".

actuellement:
mongo_connect[p_collection].update(find,update,upsert=True)

proposition:
mongo_connect[p_collection].update(find,update,upsert=True,multi=True)

documentation:
https://docs.mongodb.org/v2.4/reference/method/db.collection.update/

**Comment by fabiolab** [comment]
Fixed since version 1.4.9
